
- name: copy certificates
  copy: src=ssl/controller.tar dest=/tmp/ssl.tar
- command: mkdir -p /etc/kubernetes/ssl
- command: tar -C /etc/kubernetes/ssl -xf /tmp/ssl.tar

- name: copy installation script
  copy: src=user-data dest=/tmp/vagrantfile-user-data
- command: mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/
  
- name: start etcd
  raw: systemctl restart etcd
# - name: install kube
#   script: user-data.sh