---

# detect proxy
- name: Creates directory
  file: path=/opt/script state=directory
  
- name: copy proxy detection script
  become: yes
  copy: src=detect_proxy.sh dest=/opt/script/detect_proxy.sh mode=0755
  
- name: test proxy
  become: yes
  shell: /opt/script/detect_proxy.sh
  register: proxy_result

- name: set
  set_fact:
    has_proxy: true
    proxy_url: "{{ proxy_result.stdout }}"
  when: "'http://' in proxy_result.stdout"
  
- debug: msg="{{ proxy_url }}, {{ has_proxy }} "
   
 # now transfer certificates  
- name: Creates directory
  file: path=/etc/kubernetes/ssl state=directory
  
- unarchive: src=ssl/controller.tar dest=/etc/kubernetes/ssl

# set required environment
- name: set /etc/environment
  template: src=environment.j2 dest=/etc/environment
  
# and install kubernetes
- name: copy kubernetes installation script
  template: src=user-data.j2 dest=/tmp/user-data

- name: run install script
  become: yes
  command: coreos-cloudinit --from-file=/tmp/user-data
  
# now install and configure kubectl  
- name: Creates directory
  file: path=/opt/config state=directory
  
- name: install kubectl
  become: yes
  copy: src=kubectl dest=/opt/bin/kubectl mode=0755
  
- name: configure kubectl
  template: src=kubeconfig.j2 dest=/opt/config/kubeconfig
  environment: 
    KUBECONFIG: :/opt/config/kubeconfig
    
- command: kubectl config use-context single
  args:
    chdir: /opt/config

# install helmc and our helm repository 
- name: install helmc
  copy: src=helmc dest=/opt/bin/helmc mode=0755

- name: check if repository already exist
  stat: path=/opt/helm
  register: dir
  
- name: install helm repository
  command: git clone https://github.com/spicter/helm.git
  args: 
    chdir: /opt
  when: dir.stat.islnk is not defined
  
- name: update helm repositories
  become: yes
  command: helmc --home /opt/helm update 

# wait until api-server is up
- name: wait until api-server is up
  wait_for: port=8080 delay=5
    
- name: wait until kube-system services are up
  copy: src=wait_for_kubesystem_is_up.sh dest=/opt/script/wait_for_kubesystem_is_up.sh mode=0755
- command: sh /opt/script/wait_for_kubesystem_is_up.sh
  
# install all kube-system services
- name: install all kube-system services
  include: system-services.yml

