---
# todo: set environment var SINGLE_NODE so that all can be handled the normal way

# - hosts: all
  
# special handling of kubernetes setup on a single node
# - include: 01_system-layer.yml
# but the rest will be equal
# - include: ../../02_data-layer.yml

- name: install kubernetes (etcd, flannel, master, nodes)
  hosts: coreos
  gather_facts: False
  roles:
    - coreos-bootstrap
    - system-layer
  become: true