# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_IP = "172.12.8.100"
CLUSTER_IP="10.3.0.1"

NODE_MEMORY_SIZE = 8192

system("mkdir -p ssl && ./../../../lib/init-ssl-ca ssl") or abort ("failed generating SSL CA artifacts")
system("./../../../lib/init-ssl ssl apiserver controller IP.1=#{NODE_IP},IP.2=#{CLUSTER_IP}") or abort ("failed generating SSL certificate artifacts")
system("./../../../lib/init-ssl ssl admin kube-admin") or abort("failed generating admin SSL artifacts")

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-proxyconf")
     config.proxy.http  =  "http://proxy.ct-dmz.cardtech.de:8080"
     config.proxy.https =  "http://proxy.ct-dmz.cardtech.de:8080"
     config.proxy.no_proxy = "localhost,127.0.0.1"
  end
  
  config.vm.box = "coreos-alpha"
  config.vm.box_version = ">= 766.0.0"
  config.vm.box_url = "http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"

  config.ssh.insert_key = false
  
  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  
  config.vm.network :private_network, ip: NODE_IP
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      vb.name = "single-kube"
      vb.check_guest_additions = false
      vb.functional_vboxsf     = false  
    # Customize the amount of memory on the VM:
      vb.memory = NODE_MEMORY_SIZE
  end
  
  config.vm.hostname = "single01.spicter.com"

#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "v"
#    ansible.playbook = "site.yml"
#  end
end
