# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "coreos-alpha"
  config.vm.box_version = ">= 766.0.0"
  config.vm.box_url = "http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"

  config.ssh.insert_key = false
  
  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  
  config.vm.network :private_network, ip: "172.12.8.100"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      vb.name = "single-kube"
      vb.check_guest_additions = false
      vb.functional_vboxsf     = false  
    # Customize the amount of memory on the VM:
      vb.memory = "8192"
  end
  
  config.vm.hostname = "single01.spicter.com"

#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "v"
#    ansible.playbook = "site.yml"
#  end
end
